export interface Padding {
  ['p-0']: boolean; // padding: 0px;
  ['px-0']: boolean; // padding-left: 0px, padding-right: 0px;
  ['py-0']: boolean; // padding-top: 0px; padding-bottom: 0px;
  ['pt-0']: boolean; // padding-top: 0px;
  ['pr-0']: boolean; // padding-right: 0px;
  ['pb-0']: boolean; // padding-bottom: 0px;
  ['pl-0']: boolean; // padding-left: 0px;
  ['p-px']: boolean; // padding: 1px;
  ['px-px']: boolean; // padding-left: 1px; padding-right: 1px;
  ['py-px']: boolean; // padding-top: 1px; padding-bottom: 1px;
  ['pt-px']: boolean; // padding-top: 1px;
  ['pr-px']: boolean; // padding-right: 1px;
  ['pb-px']: boolean; // padding-bottom: 1px;
  ['pl-px']: boolean; // padding-left: 1px;
  ['p-0.5']: boolean; // padding: 0.125rem;
  ['px-0.5']: boolean; // padding-left: 0.125rem; padding-right: 0.125rem;
  ['py-0.5']: boolean; // padding-top: 0.125rem; padding-bottom: 0.125rem;
  ['pt-0.5']: boolean; // padding-top: 0.125rem;
  ['pr-0.5']: boolean; // padding-right: 0.125rem;
  ['pb-0.5']: boolean; // padding-bottom: 0.125rem;
  ['pl-0.5']: boolean; // padding-left: 0.125rem;
  ['p-1']: boolean; // padding: 0.25rem;
  ['px-1']: boolean; // padding-left: 0.25rem; padding-right: 0.25rem;
  ['py-1']: boolean; // padding-top: 0.25rem; padding-bottom: 0.25rem;
  ['pt-1']: boolean; // padding-top: 0.25rem;
  ['pr-1']: boolean; // padding-right: 0.25rem;
  ['pb-1']: boolean; // padding-bottom: 0.25rem;
  ['pl-1']: boolean; // padding-left: 0.25rem;
  ['p-1.5']: boolean; // padding: 0.375rem;
  ['px-1.5']: boolean; // padding-left: 0.375rem; padding-right: 0.375rem;
  ['py-1.5']: boolean; // padding-top: 0.375rem; padding-bottom: 0.375rem;
  ['pt-1.5']: boolean; // padding-top: 0.375rem;
  ['pr-1.5']: boolean; // padding-right: 0.375rem;
  ['pb-1.5']: boolean; // padding-bottom: 0.375rem;
  ['pl-1.5']: boolean; // padding-left: 0.375rem;
  ['p-2']: boolean; // padding: 0.5rem;
  ['px-2']: boolean; // padding-left: 0.5rem; padding-right: 0.5rem;
  ['py-2']: boolean; // padding-top: 0.5rem;:boolean // padding-bottom: 0.5rem;
  ['pt-2']: boolean; // padding-top: 0.5rem;
  ['pr-2']: boolean; // padding-right: 0.5rem;
  ['pb-2']: boolean; // padding-bottom: 0.5rem;
  ['pl-2']: boolean; // padding-left: 0.5rem;
  ['p-2.5']: boolean; // padding: 0.625rem;
  ['px-2.5']: boolean; // padding-left: 0.625rem;:boolean // padding-right: 0.625rem;
  ['py-2.5']: boolean; // padding-top: 0.625rem;:boolean // padding-bottom: 0.625rem;
  ['pt-2.5']: boolean; // padding-top: 0.625rem;
  ['pr-2.5']: boolean; // padding-right: 0.625rem;
  ['pb-2.5']: boolean; // padding-bottom: 0.625rem;
  ['pl-2.5']: boolean; // padding-left: 0.625rem;
  ['p-3']: boolean; // padding: 0.75rem;
  ['px-3']: boolean; // padding-left: 0.75rem;:boolean // padding-right: 0.75rem;
  ['py-3']: boolean; // padding-top: 0.75rem;:boolean // padding-bottom: 0.75rem;
  ['pt-3']: boolean; // padding-top: 0.75rem;
  ['pr-3']: boolean; // padding-right: 0.75rem;
  ['pb-3']: boolean; // padding-bottom: 0.75rem;
  ['pl-3']: boolean; // padding-left: 0.75rem;
  ['p-3.5']: boolean; // padding: 0.875rem;
  ['px-3.5']: boolean; // padding-left: 0.875rem;:boolean // padding-right: 0.875rem;
  ['py-3.5']: boolean; // padding-top: 0.875rem;:boolean // padding-bottom: 0.875rem;
  ['pt-3.5']: boolean; // padding-top: 0.875rem;
  ['pr-3.5']: boolean; // padding-right: 0.875rem;
  ['pb-3.5']: boolean; // padding-bottom: 0.875rem;
  ['pl-3.5']: boolean; // padding-left: 0.875rem;
  ['p-4']: boolean; // padding: 1rem;
  ['px-4']: boolean; // padding-left: 1rem;:boolean // padding-right: 1rem;
  ['py-4']: boolean; // padding-top: 1rem;:boolean // padding-bottom: 1rem;
  ['pt-4']: boolean; // padding-top: 1rem;
  ['pr-4']: boolean; // padding-right: 1rem;
  ['pb-4']: boolean; // padding-bottom: 1rem;
  ['pl-4']: boolean; // padding-left: 1rem;
  ['p-5']: boolean; // padding: 1.25rem;
  ['px-5']: boolean; // padding-left: 1.25rem;:boolean // padding-right: 1.25rem;
  ['py-5']: boolean; // padding-top: 1.25rem;:boolean // padding-bottom: 1.25rem;
  ['pt-5']: boolean; // padding-top: 1.25rem;
  ['pr-5']: boolean; // padding-right: 1.25rem;
  ['pb-5']: boolean; // padding-bottom: 1.25rem;
  ['pl-5']: boolean; // padding-left: 1.25rem;
  ['p-6']: boolean; // padding: 1.5rem;
  ['px-6']: boolean; // padding-left: 1.5rem;:boolean // padding-right: 1.5rem;
  ['py-6']: boolean; // padding-top: 1.5rem;:boolean // padding-bottom: 1.5rem;
  ['pt-6']: boolean; // padding-top: 1.5rem;
  ['pr-6']: boolean; // padding-right: 1.5rem;
  ['pb-6']: boolean; // padding-bottom: 1.5rem;
  ['pl-6']: boolean; // padding-left: 1.5rem;
  ['p-7']: boolean; // padding: 1.75rem;
  ['px-7']: boolean; // padding-left: 1.75rem;:boolean // padding-right: 1.75rem;
  ['py-7']: boolean; // padding-top: 1.75rem;:boolean // padding-bottom: 1.75rem;
  ['pt-7']: boolean; // padding-top: 1.75rem;
  ['pr-7']: boolean; // padding-right: 1.75rem;
  ['pb-7']: boolean; // padding-bottom: 1.75rem;
  ['pl-7']: boolean; // padding-left: 1.75rem;
  ['p-8']: boolean; // padding: 2rem;
  ['px-8']: boolean; // padding-left: 2rem;:boolean // padding-right: 2rem;
  ['py-8']: boolean; // padding-top: 2rem;:boolean // padding-bottom: 2rem;
  ['pt-8']: boolean; // padding-top: 2rem;
  ['pr-8']: boolean; // padding-right: 2rem;
  ['pb-8']: boolean; // padding-bottom: 2rem;
  ['pl-8']: boolean; // padding-left: 2rem;
  ['p-9']: boolean; // padding: 2.25rem;
  ['px-9']: boolean; // padding-left: 2.25rem;:boolean // padding-right: 2.25rem;
  ['py-9']: boolean; // padding-top: 2.25rem;:boolean // padding-bottom: 2.25rem;
  ['pt-9']: boolean; // padding-top: 2.25rem;
  ['pr-9']: boolean; // padding-right: 2.25rem;
  ['pb-9']: boolean; // padding-bottom: 2.25rem;
  ['pl-9']: boolean; // padding-left: 2.25rem;
  ['p-10']: boolean; // padding: 2.5rem;
  ['px-10']: boolean; // padding-left: 2.5rem;:boolean // padding-right: 2.5rem;
  ['py-10']: boolean; // padding-top: 2.5rem;:boolean // padding-bottom: 2.5rem;
  ['pt-10']: boolean; // padding-top: 2.5rem;
  ['pr-10']: boolean; // padding-right: 2.5rem;
  ['pb-10']: boolean; // padding-bottom: 2.5rem;
  ['pl-10']: boolean; // padding-left: 2.5rem;
  ['p-11']: boolean; // padding: 2.75rem;
  ['px-11']: boolean; // padding-left: 2.75rem;:boolean // padding-right: 2.75rem;
  ['py-11']: boolean; // padding-top: 2.75rem;:boolean // padding-bottom: 2.75rem;
  ['pt-11']: boolean; // padding-top: 2.75rem;
  ['pr-11']: boolean; // padding-right: 2.75rem;
  ['pb-11']: boolean; // padding-bottom: 2.75rem;
  ['pl-11']: boolean; // padding-left: 2.75rem;
  ['p-12']: boolean; // padding: 3rem;
  ['px-12']: boolean; // padding-left: 3rem;:boolean // padding-right: 3rem;
  ['py-12']: boolean; // padding-top: 3rem;:boolean // padding-bottom: 3rem;
  ['pt-12']: boolean; // padding-top: 3rem;
  ['pr-12']: boolean; // padding-right: 3rem;
  ['pb-12']: boolean; // padding-bottom: 3rem;
  ['pl-12']: boolean; // padding-left: 3rem;
  ['p-14']: boolean; // padding: 3.5rem;
  ['px-14']: boolean; // padding-left: 3.5rem;:boolean // padding-right: 3.5rem;
  ['py-14']: boolean; // padding-top: 3.5rem;:boolean // padding-bottom: 3.5rem;
  ['pt-14']: boolean; // padding-top: 3.5rem;
  ['pr-14']: boolean; // padding-right: 3.5rem;
  ['pb-14']: boolean; // padding-bottom: 3.5rem;
  ['pl-14']: boolean; // padding-left: 3.5rem;
  ['p-16']: boolean; // padding: 4rem;
  ['px-16']: boolean; // padding-left: 4rem;:boolean // padding-right: 4rem;
  ['py-16']: boolean; // padding-top: 4rem;:boolean // padding-bottom: 4rem;
  ['pt-16']: boolean; // padding-top: 4rem;
  ['pr-16']: boolean; // padding-right: 4rem;
  ['pb-16']: boolean; // padding-bottom: 4rem;
  ['pl-16']: boolean; // padding-left: 4rem;
  ['p-20']: boolean; // padding: 5rem;
  ['px-20']: boolean; // padding-left: 5rem;:boolean // padding-right: 5rem;
  ['py-20']: boolean; // padding-top: 5rem;:boolean // padding-bottom: 5rem;
  ['pt-20']: boolean; // padding-top: 5rem;
  ['pr-20']: boolean; // padding-right: 5rem;
  ['pb-20']: boolean; // padding-bottom: 5rem;
  ['pl-20']: boolean; // padding-left: 5rem;
  ['p-24']: boolean; // padding: 6rem;
  ['px-24']: boolean; // padding-left: 6rem;:boolean // padding-right: 6rem;
  ['py-24']: boolean; // padding-top: 6rem;:boolean // padding-bottom: 6rem;
  ['pt-24']: boolean; // padding-top: 6rem;
  ['pr-24']: boolean; // padding-right: 6rem;
  ['pb-24']: boolean; // padding-bottom: 6rem;
  ['pl-24']: boolean; // padding-left: 6rem;
  ['p-28']: boolean; // padding: 7rem;
  ['px-28']: boolean; // padding-left: 7rem;:boolean // padding-right: 7rem;
  ['py-28']: boolean; // padding-top: 7rem;:boolean // padding-bottom: 7rem;
  ['pt-28']: boolean; // padding-top: 7rem;
  ['pr-28']: boolean; // padding-right: 7rem;
  ['pb-28']: boolean; // padding-bottom: 7rem;
  ['pl-28']: boolean; // padding-left: 7rem;
  ['p-32']: boolean; // padding: 8rem;
  ['px-32']: boolean; // padding-left: 8rem;:boolean // padding-right: 8rem;
  ['py-32']: boolean; // padding-top: 8rem;:boolean // padding-bottom: 8rem;
  ['pt-32']: boolean; // padding-top: 8rem;
  ['pr-32']: boolean; // padding-right: 8rem;
  ['pb-32']: boolean; // padding-bottom: 8rem;
  ['pl-32']: boolean; // padding-left: 8rem;
  ['p-36']: boolean; // padding: 9rem;
  ['px-36']: boolean; // padding-left: 9rem;:boolean // padding-right: 9rem;
  ['py-36']: boolean; // padding-top: 9rem;:boolean // padding-bottom: 9rem;
  ['pt-36']: boolean; // padding-top: 9rem;
  ['pr-36']: boolean; // padding-right: 9rem;
  ['pb-36']: boolean; // padding-bottom: 9rem;
  ['pl-36']: boolean; // padding-left: 9rem;
  ['p-40']: boolean; // padding: 10rem;
  ['px-40']: boolean; // padding-left: 10rem;:boolean // padding-right: 10rem;
  ['py-40']: boolean; // padding-top: 10rem;:boolean // padding-bottom: 10rem;
  ['pt-40']: boolean; // padding-top: 10rem;
  ['pr-40']: boolean; // padding-right: 10rem;
  ['pb-40']: boolean; // padding-bottom: 10rem;
  ['pl-40']: boolean; // padding-left: 10rem;
  ['p-44']: boolean; // padding: 11rem;
  ['px-44']: boolean; // padding-left: 11rem;:boolean // padding-right: 11rem;
  ['py-44']: boolean; // padding-top: 11rem;:boolean // padding-bottom: 11rem;
  ['pt-44']: boolean; // padding-top: 11rem;
  ['pr-44']: boolean; // padding-right: 11rem;
  ['pb-44']: boolean; // padding-bottom: 11rem;
  ['pl-44']: boolean; // padding-left: 11rem;
  ['p-48']: boolean; // padding: 12rem;
  ['px-48']: boolean; // padding-left: 12rem;:boolean // padding-right: 12rem;
  ['py-48']: boolean; // padding-top: 12rem;:boolean // padding-bottom: 12rem;
  ['pt-48']: boolean; // padding-top: 12rem;
  ['pr-48']: boolean; // padding-right: 12rem;
  ['pb-48']: boolean; // padding-bottom: 12rem;
  ['pl-48']: boolean; // padding-left: 12rem;
  ['p-52']: boolean; // padding: 13rem;
  ['px-52']: boolean; // padding-left: 13rem;:boolean // padding-right: 13rem;
  ['py-52']: boolean; // padding-top: 13rem;:boolean // padding-bottom: 13rem;
  ['pt-52']: boolean; // padding-top: 13rem;
  ['pr-52']: boolean; // padding-right: 13rem;
  ['pb-52']: boolean; // padding-bottom: 13rem;
  ['pl-52']: boolean; // padding-left: 13rem;
  ['p-56']: boolean; // padding: 14rem;
  ['px-56']: boolean; // padding-left: 14rem;:boolean // padding-right: 14rem;
  ['py-56']: boolean; // padding-top: 14rem;:boolean // padding-bottom: 14rem;
  ['pt-56']: boolean; // padding-top: 14rem;
  ['pr-56']: boolean; // padding-right: 14rem;
  ['pb-56']: boolean; // padding-bottom: 14rem;
  ['pl-56']: boolean; // padding-left: 14rem;
  ['p-60']: boolean; // padding: 15rem;
  ['px-60']: boolean; // padding-left: 15rem;:boolean // padding-right: 15rem;
  ['py-60']: boolean; // padding-top: 15rem;:boolean // padding-bottom: 15rem;
  ['pt-60']: boolean; // padding-top: 15rem;
  ['pr-60']: boolean; // padding-right: 15rem;
  ['pb-60']: boolean; // padding-bottom: 15rem;
  ['pl-60']: boolean; // padding-left: 15rem;
  ['p-64']: boolean; // padding: 16rem;
  ['px-64']: boolean; // padding-left: 16rem;:boolean // padding-right: 16rem;
  ['py-64']: boolean; // padding-top: 16rem;:boolean // padding-bottom: 16rem;
  ['pt-64']: boolean; // padding-top: 16rem;
  ['pr-64']: boolean; // padding-right: 16rem;
  ['pb-64']: boolean; // padding-bottom: 16rem;
  ['pl-64']: boolean; // padding-left: 16rem;
  ['p-72']: boolean; // padding: 18rem;
  ['px-72']: boolean; // padding-left: 18rem;:boolean // padding-right: 18rem;
  ['py-72']: boolean; // padding-top: 18rem;:boolean // padding-bottom: 18rem;
  ['pt-72']: boolean; // padding-top: 18rem;
  ['pr-72']: boolean; // padding-right: 18rem;
  ['pb-72']: boolean; // padding-bottom: 18rem;
  ['pl-72']: boolean; // padding-left: 18rem;
  ['p-80']: boolean; // padding: 20rem;
  ['px-80']: boolean; // padding-left: 20rem;:boolean // padding-right: 20rem;
  ['py-80']: boolean; // padding-top: 20rem;:boolean // padding-bottom: 20rem;
  ['pt-80']: boolean; // padding-top: 20rem;
  ['pr-80']: boolean; // padding-right: 20rem;
  ['pb-80']: boolean; // padding-bottom: 20rem;
  ['pl-80']: boolean; // padding-left: 20rem;
  ['p-96']: boolean; // padding: 24rem;
  ['px-96']: boolean; // padding-left: 24rem;:boolean // padding-right: 24rem;
  ['py-96']: boolean; // padding-top: 24rem;:boolean // padding-bottom: 24rem;
  ['pt-96']: boolean; // padding-top: 24rem;
  ['pr-96']: boolean; // padding-right: 24rem;
  ['pb-96']: boolean; // padding-bottom: 24rem;
  ['pl-96']: boolean; // padding-left: 24rem;
}
