export interface Margin {
  ['m-0']: boolean; //margin: 0px;
  ['mx-0']: boolean; //margin-left: 0px; boolean //margin-right: 0px;
  ['my-0']: boolean; //margin-top: 0px; boolean //margin-bottom: 0px;
  ['mt-0']: boolean; //margin-top: 0px;
  ['mr-0']: boolean; //margin-right: 0px;
  ['mb-0']: boolean; //margin-bottom: 0px;
  ['ml-0']: boolean; //margin-left: 0px;
  ['m-px']: boolean; //margin: 1px;
  ['mx-px']: boolean; //margin-left: 1px; boolean //margin-right: 1px;
  ['my-px']: boolean; //margin-top: 1px; boolean //margin-bottom: 1px;
  ['mt-px']: boolean; //margin-top: 1px;
  ['mr-px']: boolean; //margin-right: 1px;
  ['mb-px']: boolean; //margin-bottom: 1px;
  ['ml-px']: boolean; //margin-left: 1px;
  ['m-0.5']: boolean; //margin: 0.125rem;
  ['mx-0.5']: boolean; //margin-left: 0.125rem; boolean //margin-right: 0.125rem;
  ['my-0.5']: boolean; //margin-top: 0.125rem; boolean //margin-bottom: 0.125rem;
  ['mt-0.5']: boolean; //margin-top: 0.125rem;
  ['mr-0.5']: boolean; //margin-right: 0.125rem;
  ['mb-0.5']: boolean; //margin-bottom: 0.125rem;
  ['ml-0.5']: boolean; //margin-left: 0.125rem;
  ['m-1']: boolean; //margin: 0.25rem;
  ['mx-1']: boolean; //margin-left: 0.25rem; boolean //margin-right: 0.25rem;
  ['my-1']: boolean; //margin-top: 0.25rem; boolean //margin-bottom: 0.25rem;
  ['mt-1']: boolean; //margin-top: 0.25rem;
  ['mr-1']: boolean; //margin-right: 0.25rem;
  ['mb-1']: boolean; //margin-bottom: 0.25rem;
  ['ml-1']: boolean; //margin-left: 0.25rem;
  ['m-1.5']: boolean; //margin: 0.375rem;
  ['mx-1.5']: boolean; //margin-left: 0.375rem; boolean //margin-right: 0.375rem;
  ['my-1.5']: boolean; //margin-top: 0.375rem; boolean //margin-bottom: 0.375rem;
  ['mt-1.5']: boolean; //margin-top: 0.375rem;
  ['mr-1.5']: boolean; //margin-right: 0.375rem;
  ['mb-1.5']: boolean; //margin-bottom: 0.375rem;
  ['ml-1.5']: boolean; //margin-left: 0.375rem;
  ['m-2']: boolean; //margin: 0.5rem;
  ['mx-2']: boolean; //margin-left: 0.5rem; boolean //margin-right: 0.5rem;
  ['my-2']: boolean; //margin-top: 0.5rem; boolean //margin-bottom: 0.5rem;
  ['mt-2']: boolean; //margin-top: 0.5rem;
  ['mr-2']: boolean; //margin-right: 0.5rem;
  ['mb-2']: boolean; //margin-bottom: 0.5rem;
  ['ml-2']: boolean; //margin-left: 0.5rem;
  ['m-2.5']: boolean; //margin: 0.625rem;
  ['mx-2.5']: boolean; //margin-left: 0.625rem; boolean //margin-right: 0.625rem;
  ['my-2.5']: boolean; //margin-top: 0.625rem; boolean //margin-bottom: 0.625rem;
  ['mt-2.5']: boolean; //margin-top: 0.625rem;
  ['mr-2.5']: boolean; //margin-right: 0.625rem;
  ['mb-2.5']: boolean; //margin-bottom: 0.625rem;
  ['ml-2.5']: boolean; //margin-left: 0.625rem;
  ['m-3']: boolean; //margin: 0.75rem;
  ['mx-3']: boolean; //margin-left: 0.75rem; boolean //margin-right: 0.75rem;
  ['my-3']: boolean; //margin-top: 0.75rem; boolean //margin-bottom: 0.75rem;
  ['mt-3']: boolean; //margin-top: 0.75rem;
  ['mr-3']: boolean; //margin-right: 0.75rem;
  ['mb-3']: boolean; //margin-bottom: 0.75rem;
  ['ml-3']: boolean; //margin-left: 0.75rem;
  ['m-3.5']: boolean; //margin: 0.875rem;
  ['mx-3.5']: boolean; //margin-left: 0.875rem; boolean //margin-right: 0.875rem;
  ['my-3.5']: boolean; //margin-top: 0.875rem; boolean //margin-bottom: 0.875rem;
  ['mt-3.5']: boolean; //margin-top: 0.875rem;
  ['mr-3.5']: boolean; //margin-right: 0.875rem;
  ['mb-3.5']: boolean; //margin-bottom: 0.875rem;
  ['ml-3.5']: boolean; //margin-left: 0.875rem;
  ['m-4']: boolean; //margin: 1rem;
  ['mx-4']: boolean; //margin-left: 1rem; boolean //margin-right: 1rem;
  ['my-4']: boolean; //margin-top: 1rem; boolean //margin-bottom: 1rem;
  ['mt-4']: boolean; //margin-top: 1rem;
  ['mr-4']: boolean; //margin-right: 1rem;
  ['mb-4']: boolean; //margin-bottom: 1rem;
  ['ml-4']: boolean; //margin-left: 1rem;
  ['m-5']: boolean; //margin: 1.25rem;
  ['mx-5']: boolean; //margin-left: 1.25rem; boolean //margin-right: 1.25rem;
  ['my-5']: boolean; //margin-top: 1.25rem; boolean //margin-bottom: 1.25rem;
  ['mt-5']: boolean; //margin-top: 1.25rem;
  ['mr-5']: boolean; //margin-right: 1.25rem;
  ['mb-5']: boolean; //margin-bottom: 1.25rem;
  ['ml-5']: boolean; //margin-left: 1.25rem;
  ['m-6']: boolean; //margin: 1.5rem;
  ['mx-6']: boolean; //margin-left: 1.5rem; boolean //margin-right: 1.5rem;
  ['my-6']: boolean; //margin-top: 1.5rem; boolean //margin-bottom: 1.5rem;
  ['mt-6']: boolean; //margin-top: 1.5rem;
  ['mr-6']: boolean; //margin-right: 1.5rem;
  ['mb-6']: boolean; //margin-bottom: 1.5rem;
  ['ml-6']: boolean; //margin-left: 1.5rem;
  ['m-7']: boolean; //margin: 1.75rem;
  ['mx-7']: boolean; //margin-left: 1.75rem; boolean //margin-right: 1.75rem;
  ['my-7']: boolean; //margin-top: 1.75rem; boolean //margin-bottom: 1.75rem;
  ['mt-7']: boolean; //margin-top: 1.75rem;
  ['mr-7']: boolean; //margin-right: 1.75rem;
  ['mb-7']: boolean; //margin-bottom: 1.75rem;
  ['ml-7']: boolean; //margin-left: 1.75rem;
  ['m-8']: boolean; //margin: 2rem;
  ['mx-8']: boolean; //margin-left: 2rem; boolean //margin-right: 2rem;
  ['my-8']: boolean; //margin-top: 2rem; boolean //margin-bottom: 2rem;
  ['mt-8']: boolean; //margin-top: 2rem;
  ['mr-8']: boolean; //margin-right: 2rem;
  ['mb-8']: boolean; //margin-bottom: 2rem;
  ['ml-8']: boolean; //margin-left: 2rem;
  ['m-9']: boolean; //margin: 2.25rem;
  ['mx-9']: boolean; //margin-left: 2.25rem; boolean //margin-right: 2.25rem;
  ['my-9']: boolean; //margin-top: 2.25rem; boolean //margin-bottom: 2.25rem;
  ['mt-9']: boolean; //margin-top: 2.25rem;
  ['mr-9']: boolean; //margin-right: 2.25rem;
  ['mb-9']: boolean; //margin-bottom: 2.25rem;
  ['ml-9']: boolean; //margin-left: 2.25rem;
  ['m-10']: boolean; //margin: 2.5rem;
  ['mx-10']: boolean; //margin-left: 2.5rem; boolean //margin-right: 2.5rem;
  ['my-10']: boolean; //margin-top: 2.5rem; boolean //margin-bottom: 2.5rem;
  ['mt-10']: boolean; //margin-top: 2.5rem;
  ['mr-10']: boolean; //margin-right: 2.5rem;
  ['mb-10']: boolean; //margin-bottom: 2.5rem;
  ['ml-10']: boolean; //margin-left: 2.5rem;
  ['m-11']: boolean; //margin: 2.75rem;
  ['mx-11']: boolean; //margin-left: 2.75rem; boolean //margin-right: 2.75rem;
  ['my-11']: boolean; //margin-top: 2.75rem; boolean //margin-bottom: 2.75rem;
  ['mt-11']: boolean; //margin-top: 2.75rem;
  ['mr-11']: boolean; //margin-right: 2.75rem;
  ['mb-11']: boolean; //margin-bottom: 2.75rem;
  ['ml-11']: boolean; //margin-left: 2.75rem;
  ['m-12']: boolean; //margin: 3rem;
  ['mx-12']: boolean; //margin-left: 3rem; boolean //margin-right: 3rem;
  ['my-12']: boolean; //margin-top: 3rem; boolean //margin-bottom: 3rem;
  ['mt-12']: boolean; //margin-top: 3rem;
  ['mr-12']: boolean; //margin-right: 3rem;
  ['mb-12']: boolean; //margin-bottom: 3rem;
  ['ml-12']: boolean; //margin-left: 3rem;
  ['m-14']: boolean; //margin: 3.5rem;
  ['mx-14']: boolean; //margin-left: 3.5rem; boolean //margin-right: 3.5rem;
  ['my-14']: boolean; //margin-top: 3.5rem; boolean //margin-bottom: 3.5rem;
  ['mt-14']: boolean; //margin-top: 3.5rem;
  ['mr-14']: boolean; //margin-right: 3.5rem;
  ['mb-14']: boolean; //margin-bottom: 3.5rem;
  ['ml-14']: boolean; //margin-left: 3.5rem;
  ['m-16']: boolean; //margin: 4rem;
  ['mx-16']: boolean; //margin-left: 4rem; boolean //margin-right: 4rem;
  ['my-16']: boolean; //margin-top: 4rem; boolean //margin-bottom: 4rem;
  ['mt-16']: boolean; //margin-top: 4rem;
  ['mr-16']: boolean; //margin-right: 4rem;
  ['mb-16']: boolean; //margin-bottom: 4rem;
  ['ml-16']: boolean; //margin-left: 4rem;
  ['m-20']: boolean; //margin: 5rem;
  ['mx-20']: boolean; //margin-left: 5rem; boolean //margin-right: 5rem;
  ['my-20']: boolean; //margin-top: 5rem; boolean //margin-bottom: 5rem;
  ['mt-20']: boolean; //margin-top: 5rem;
  ['mr-20']: boolean; //margin-right: 5rem;
  ['mb-20']: boolean; //margin-bottom: 5rem;
  ['ml-20']: boolean; //margin-left: 5rem;
  ['m-24']: boolean; //margin: 6rem;
  ['mx-24']: boolean; //margin-left: 6rem; boolean //margin-right: 6rem;
  ['my-24']: boolean; //margin-top: 6rem; boolean //margin-bottom: 6rem;
  ['mt-24']: boolean; //margin-top: 6rem;
  ['mr-24']: boolean; //margin-right: 6rem;
  ['mb-24']: boolean; //margin-bottom: 6rem;
  ['ml-24']: boolean; //margin-left: 6rem;
  ['m-28']: boolean; //margin: 7rem;
  ['mx-28']: boolean; //margin-left: 7rem; boolean //margin-right: 7rem;
  ['my-28']: boolean; //margin-top: 7rem; boolean //margin-bottom: 7rem;
  ['mt-28']: boolean; //margin-top: 7rem;
  ['mr-28']: boolean; //margin-right: 7rem;
  ['mb-28']: boolean; //margin-bottom: 7rem;
  ['ml-28']: boolean; //margin-left: 7rem;
  ['m-32']: boolean; //margin: 8rem;
  ['mx-32']: boolean; //margin-left: 8rem; boolean //margin-right: 8rem;
  ['my-32']: boolean; //margin-top: 8rem; boolean //margin-bottom: 8rem;
  ['mt-32']: boolean; //margin-top: 8rem;
  ['mr-32']: boolean; //margin-right: 8rem;
  ['mb-32']: boolean; //margin-bottom: 8rem;
  ['ml-32']: boolean; //margin-left: 8rem;
  ['m-36']: boolean; //margin: 9rem;
  ['mx-36']: boolean; //margin-left: 9rem; boolean //margin-right: 9rem;
  ['my-36']: boolean; //margin-top: 9rem; boolean //margin-bottom: 9rem;
  ['mt-36']: boolean; //margin-top: 9rem;
  ['mr-36']: boolean; //margin-right: 9rem;
  ['mb-36']: boolean; //margin-bottom: 9rem;
  ['ml-36']: boolean; //margin-left: 9rem;
  ['m-40']: boolean; //margin: 10rem;
  ['mx-40']: boolean; //margin-left: 10rem; boolean //margin-right: 10rem;
  ['my-40']: boolean; //margin-top: 10rem; boolean //margin-bottom: 10rem;
  ['mt-40']: boolean; //margin-top: 10rem;
  ['mr-40']: boolean; //margin-right: 10rem;
  ['mb-40']: boolean; //margin-bottom: 10rem;
  ['ml-40']: boolean; //margin-left: 10rem;
  ['m-44']: boolean; //margin: 11rem;
  ['mx-44']: boolean; //margin-left: 11rem; boolean //margin-right: 11rem;
  ['my-44']: boolean; //margin-top: 11rem; boolean //margin-bottom: 11rem;
  ['mt-44']: boolean; //margin-top: 11rem;
  ['mr-44']: boolean; //margin-right: 11rem;
  ['mb-44']: boolean; //margin-bottom: 11rem;
  ['ml-44']: boolean; //margin-left: 11rem;
  ['m-48']: boolean; //margin: 12rem;
  ['mx-48']: boolean; //margin-left: 12rem; boolean //margin-right: 12rem;
  ['my-48']: boolean; //margin-top: 12rem; boolean //margin-bottom: 12rem;
  ['mt-48']: boolean; //margin-top: 12rem;
  ['mr-48']: boolean; //margin-right: 12rem;
  ['mb-48']: boolean; //margin-bottom: 12rem;
  ['ml-48']: boolean; //margin-left: 12rem;
  ['m-52']: boolean; //margin: 13rem;
  ['mx-52']: boolean; //margin-left: 13rem; boolean //margin-right: 13rem;
  ['my-52']: boolean; //margin-top: 13rem; boolean //margin-bottom: 13rem;
  ['mt-52']: boolean; //margin-top: 13rem;
  ['mr-52']: boolean; //margin-right: 13rem;
  ['mb-52']: boolean; //margin-bottom: 13rem;
  ['ml-52']: boolean; //margin-left: 13rem;
  ['m-56']: boolean; //margin: 14rem;
  ['mx-56']: boolean; //margin-left: 14rem; boolean //margin-right: 14rem;
  ['my-56']: boolean; //margin-top: 14rem; boolean //margin-bottom: 14rem;
  ['mt-56']: boolean; //margin-top: 14rem;
  ['mr-56']: boolean; //margin-right: 14rem;
  ['mb-56']: boolean; //margin-bottom: 14rem;
  ['ml-56']: boolean; //margin-left: 14rem;
  ['m-60']: boolean; //margin: 15rem;
  ['mx-60']: boolean; //margin-left: 15rem; boolean //margin-right: 15rem;
  ['my-60']: boolean; //margin-top: 15rem; boolean //margin-bottom: 15rem;
  ['mt-60']: boolean; //margin-top: 15rem;
  ['mr-60']: boolean; //margin-right: 15rem;
  ['mb-60']: boolean; //margin-bottom: 15rem;
  ['ml-60']: boolean; //margin-left: 15rem;
  ['m-64']: boolean; //margin: 16rem;
  ['mx-64']: boolean; //margin-left: 16rem; boolean //margin-right: 16rem;
  ['my-64']: boolean; //margin-top: 16rem; boolean //margin-bottom: 16rem;
  ['mt-64']: boolean; //margin-top: 16rem;
  ['mr-64']: boolean; //margin-right: 16rem;
  ['mb-64']: boolean; //margin-bottom: 16rem;
  ['ml-64']: boolean; //margin-left: 16rem;
  ['m-72']: boolean; //margin: 18rem;
  ['mx-72']: boolean; //margin-left: 18rem; boolean //margin-right: 18rem;
  ['my-72']: boolean; //margin-top: 18rem; boolean //margin-bottom: 18rem;
  ['mt-72']: boolean; //margin-top: 18rem;
  ['mr-72']: boolean; //margin-right: 18rem;
  ['mb-72']: boolean; //margin-bottom: 18rem;
  ['ml-72']: boolean; //margin-left: 18rem;
  ['m-80']: boolean; //margin: 20rem;
  ['mx-80']: boolean; //margin-left: 20rem; boolean //margin-right: 20rem;
  ['my-80']: boolean; //margin-top: 20rem; boolean //margin-bottom: 20rem;
  ['mt-80']: boolean; //margin-top: 20rem;
  ['mr-80']: boolean; //margin-right: 20rem;
  ['mb-80']: boolean; //margin-bottom: 20rem;
  ['ml-80']: boolean; //margin-left: 20rem;
  ['m-96']: boolean; //margin: 24rem;
  ['mx-96']: boolean; //margin-left: 24rem; boolean //margin-right: 24rem;
  ['my-96']: boolean; //margin-top: 24rem; boolean //margin-bottom: 24rem;
  ['mt-96']: boolean; //margin-top: 24rem;
  ['mr-96']: boolean; //margin-right: 24rem;
  ['mb-96']: boolean; //margin-bottom: 24rem;
  ['ml-96']: boolean; //margin-left: 24rem;
  ['m-auto']: boolean; //margin: auto;
  ['mx-auto']: boolean; //margin-left: auto; boolean //margin-right: auto;
  ['my-auto']: boolean; //margin-top: auto; boolean //margin-bottom: auto;
  ['mt-auto']: boolean; //margin-top: auto;
  ['mr-auto']: boolean; //margin-right: auto;
  ['mb-auto']: boolean; //margin-bottom: auto;
  ['ml-auto']: boolean; //margin-left: auto;
}
